// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Galleria.Models
{
    public partial class Commissions
    {
        public int CommissionId { get; set; }
        public string CommissionName { get; set; }
        public int ArtistId { get; set; }
        public string CommissionImage { get; set; }
        public DateTime DatePublished { get; set; }
        public string Description { get; set; }
    }
}